stages:
  - build
  - test
  - deploy

build_app:
  stage: build
  script:
    - mvn clean install
  artifacts:
    paths:
      - ./target/petclinic.war

run_tests:
  stage: test
  script:
    - mvn test

deploy_app:
  stage: deploy
  script:
    - chmod +x script_for_deploying.sh
    - ./script_for_deploying.sh
  environment:
    name: production
    url: http://192.168.178.204/petclinic/
  only:
    - main
