stages:
    -build
    -test
    -deploy

build:
  stage: build
  script:
    - echo "Building the project..."
    - mvn compile

test:
  stage: test
  script:
    - echo "Running tests..."
    - mvn test

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    - mvn deploy


